# Generated by Django 4.2.7 on 2023-12-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_produk_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pinjam', models.CharField(max_length=100)),
                ('judul_buku', models.CharField(max_length=100)),
                ('tgl_pinjam', models.CharField(max_length=100)),
                ('kembalian', models.CharField(max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.kategori')),
            ],
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
